$(document).ready(function(){
  $("#panel1").click(function(){
    $(".js-show").toggle();
    $(".js-hidden").toggle();
  });
  $("#panel2").click(function(){
    $(".op-show").toggle();
    $(".op-hidden").toggle();
  });
  $("#panel3").click(function(){
    $(".v-show").toggle();
    $(".v-hidden").toggle();
  });
  $("#panel4").click(function(){
    $(".vn-show").toggle();
    $(".vn-hidden").toggle();
  });
  $("#panel5").click(function(){
    $(".fun-show").toggle();
    $(".fun-hidden").toggle();
  });
  $("#panel6").click(function(){
    $(".meth-show").toggle();
    $(".meth-hidden").toggle();
  });
  $("#panel7").click(function(){
    $(".arg-show").toggle();
    $(".arg-hidden").toggle();
  });
  $("#panel8").click(function(){
    $(".par-show").toggle();
    $(".par-hidden").toggle();
  });
  $("#panel9").click(function(){
    $(".ret-show").toggle();
    $(".ret-hidden").toggle();
  });
  $("#panel10").click(function(){
    $(".chan-show").toggle();
    $(".chan-hidden").toggle();
  });
  $("#panel11").click(function(){
    $(".str-show").toggle();
    $(".str-hidden").toggle();
  });
  $("#panel12").click(function(){
    $(".boo-show").toggle();
    $(".boo-hidden").toggle();
  });
  $("#panel13").click(function(){
    $(".und-show").toggle();
    $(".und-hidden").toggle();
  });
  $("#panel14").click(function(){
    $(".nan-show").toggle();
    $(".nan-hidden").toggle();
  });
  $("#panel15").click(function(){
    $(".esc-show").toggle();
    $(".esc-hidden").toggle();
  });
  $("#panel16").click(function(){
    $(".al-show").toggle();
    $(".al-hidden").toggle();
  });
  $("#panel17").click(function(){
    $(".com-show").toggle();
    $(".com-hidden").toggle();
  });
  $("#panel18").click(function(){
    $(".jq-show").toggle();
    $(".jq-hidden").toggle();
  });
  $("#panel19").click(function(){
    $(".at-show").toggle();
    $(".at-hidden").toggle();
  });
});
